language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
script: pytest ./tests
sudo: false
notifications:
  email:
    - jay_luker@harvard.edu
    - nataliemona@g.harvard.edu
env:
  AWS_DEFAULT_REGION=us-east-1
